### ISSUE TITLE
FYI: i686 builds of ga excluded, starting from f38

### ISSUE THREAD

**Issue by marcindulak** [edoapra/fedpkg#12]
https://bugzilla.redhat.com/show_bug.cgi?id=2152521

The i686 exclusion will propagate also to nwchem f38 builds.

**Comment by edoapra** [comment]
GA version 5.8.2 is out
https://github.com/GlobalArrays/ga/releases/tag/v5.8.2
It might be worth checking if the error shows up for 5.8.2

**Comment by marcindulak** [comment]
It's something openmpi dependencies related https://github.com/ofiwg/libfabric/issues/8375, and shows in a mpi hello world program. https://github.com/GlobalArrays/ga/releases/tag/v5.8.2 crashes during tests with "Segmentation fault" too https://koji.fedoraproject.org/koji/taskinfo?taskID=96380398

It's not clear to me whether an older https://github.com/nwchemgit/nwchem/releases/tag/v7.0.2-release supports a newer ga.

I'll try to enable the i686 builds when openmpi fix is in fedora.

**Comment by edoapra** [comment]
7.0.2 should work fine with ga 5.8.2
Anyhow NWChem 7.2.0 should be out soon
https://github.com/nwchemgit/nwchem/releases/tag/untagged-c26418e6bfea94d9c22e

Thanks for the details of the Fedora OpenMPI issue ... is Mpich working, instead?

**Comment by marcindulak** [comment]
mpich tests work

**Comment by edoapra** [comment]
It seems odd that Fedora builds openmpi on top of libfabric instead of UCX (if I am reading the bug reports correctly ...). As far as NWChem is concerned, UCX seems a much better choice.

**Comment by edoapra** [comment]
NWChem 7.2.0 is out https://github.com/nwchemgit/nwchem/releases/tag/v7.2.0-release
