### ISSUE TITLE
updated nwchem.spec available

### ISSUE THREAD

**Issue by marcindulak** [edoapra/fedpkg#3]
The latest spec is at https://src.fedoraproject.org/rpms/nwchem/c/406bd9b8b37781a9c617e0f29e4845014fd903bd

I simply updated to https://github.com/nwchemgit/nwchem/commit/6b5bd318870c3d6ad9168284bb3455e800383ccf due to https://bugzilla.redhat.com/show_bug.cgi?id=1793464 and the build succeeded.

**Comment by edoapra** [comment]
Thanks for the update.
I should be able to, eventually, get 7.0.0 out in February.
A minor update (5.7.1) for Global Arrays should be available, too

**Comment by edoapra** [comment]
Commit pushed https://github.com/edoapra/fedpkg/commit/210d2d7fa8c5be67a02ee4d8eebe9e5f038a508a

**Comment by edoapra** [comment]
Pushed new commit 
https://github.com/edoapra/fedpkg/commit/935dd5748f7248cf7cff3e59d8dc4796fd209f0b
It seem to fail only on f33/i686, but the ga-5.7.2 rpm might have a fix for the failure

**Comment by edoapra** [comment]
patch needed to build against ga rpm without peigs 
https://github.com/edoapra/fedpkg/commit/1ecb311f756a5f275621ec1e48c28532b90cf5c6#diff-c33df58ef66df25270afbf7b54d8f103

**Comment by marcindulak** [comment]
I would like we stop using the release_date in the spec and don't refer anymore to the "versioned" tarballs

https://github.com/edoapra/fedpkg/blob/1ecb311f756a5f275621ec1e48c28532b90cf5c6/nwchem/nwchem.spec#L8-L10

but use instead major_version and git_hash

```
%{?!major_version: %global major_version 7.0.0}
%{?!git_hash: %global git_hash 6b5bd318870c3d6ad9168284bb3455e800383ccf}
```

https://src.fedoraproject.org/rpms/nwchem/blob/49cce8446fc0434a6bca421b3f6e3448efb0185a/f/nwchem.spec#_8-9

and point to the github archive

```
Source0:		https://github.com/nwchemgit/nwchem/archive/%{git_hash}.tar.gz
```

https://src.fedoraproject.org/rpms/nwchem/blob/49cce8446fc0434a6bca421b3f6e3448efb0185a/f/nwchem.spec#_48

Such versioning is much simpler and allows one to easily test various git hashes and not being limited to only "released" tarballs.

We have now also a conflict in the changelog https://src.fedoraproject.org/rpms/nwchem/blob/49cce8446fc0434a6bca421b3f6e3448efb0185a/f/nwchem.spec#_478

Let's start using a develop branch for the changes in the repository.

**Comment by marcindulak** [comment]
I'll prepare nwchem.spec according to the comments above and test it.

https://github.com/edoapra/fedpkg/pull/9

**Comment by edoapra** [comment]
> Such versioning is much simpler and allows one to easily test various git hashes and not being limited to only "released" tarballs.

It's fine for me. My preference for using released tarballs is for two reasons: 
first that the tarballs have already been processed by the `make 64_to_32` step and
second that we do rigorous and extensive QA testing for releases, while the same cannot be said for any arbitrary git snapshot. 
Therefore, I see no problem switching from the manually created tar file mentioned above to the tar files that github automatically creates when creating a release, for example
https://github.com/nwchemgit/nwchem/archive/v7.0.0-release.tar.gz
This will get rid of the release date stamp.
If new bugs are fixed once the release is out, bug fixes go into the hotfix branch (e.g. `hotfix/release-7-0-0`), that is eventually released

**Comment by edoapra** [comment]
update https://github.com/edoapra/fedpkg/commit/dd52d5ae1ec56b3602bcdc213eeb3eb68cffb05d
Added mcscf_scalapack.patch
Switched to   https://github.com/nwchemgit/nwchem/archive/v%{major_version}-release.tar.gz tar file

**Comment by edoapra** [comment]
master branch of https://github.com/edoapra/fedpkg.nwchem is now in sync with  https://src.fedoraproject.org/rpms/nwchem
I have moved my changes to the develop branch (not fully re-tested yet)
https://github.com/edoapra/fedpkg/commit/3c53b06111531c6de6edb2ef257c4f4907a540d0

**Comment by marcindulak** [comment]
My preference for building straight from a git hash is due to the necessity of this during last year 

https://github.com/edoapra/fedpkg/blob/dd52d5ae1ec56b3602bcdc213eeb3eb68cffb05d/nwchem/nwchem.spec#L486-L494

Very often new fedora changes and mass rebuilds cause the nwchem build to fail and I've been building from hashes multiple times before we settled on a specific, unreleased hash to be used in the spec.

Is there any difference between `https://github.com/nwchemgit/nwchem/archive/v%{major_version}-release.tar.gz` and `https://github.com/nwchemgit/nwchem/archive/%{git_hash}.tar.gz` if `%{git_hash}` corresponds to the `%{major_version}` tag?

**Comment by edoapra** [comment]
> My preference for building straight from a git hash is due to the necessity of this during last year
> Very often new fedora changes and mass rebuilds cause the nwchem build to fail and I've been building from hashes multiple times before we settled on a specific, unreleased hash to be used in the spec.
> 
This might have unexpected consequences, since we do run travis ci on every github commit, but that does not cover all the code functionality. For this reason, my recommendation is to use release tar files in conjunction with patches. Patches "should'' be easy to generate (yes, I do remember some issues last here with the python3 transition ...). In other words, I do not considered a supported version code generated by a certain code snapshot at a certain time.

> Is there any difference between `https://github.com/nwchemgit/nwchem/archive/v%{major_version}-release.tar.gz` and `https://github.com/nwchemgit/nwchem/archive/%{git_hash}.tar.gz` if `%{git_hash}` corresponds to the `%{major_version}` tag?

It should be the same. It seems easier to me to track down the release version to use the github tag instead of the git hash

**Comment by marcindulak** [comment]
I'm using 

https://github.com/edoapra/fedpkg/blob/dac6f2e939acd8a962f8c268a19bb76ecb694d33/nwchem/nwchem.spec#L45

as a convenience, so I don't need to rewrite the spec every time I want to test a git hash of nwchem.

I'm not planning to regularly release git hashes that do not correspond to git tags, and if this happens such nwchem versions will be built only on rawhide, and hopefully replaced by a git hash of a tagged release as soon as the tag is made.

There are several changes (source, PKG_TOP, prep) to the spec in order to switch from tag based archive to hash based archive and back (like here https://github.com/edoapra/fedpkg/commit/63d1b9add44d9e74ad5f042fbb771570bad24b0d). This is an extra work that does not provide a value.

**Comment by marcindulak** [comment]
I think we can close this old issue.
