### ISSUE TITLE
ga.spec 5.7.1 needs to generate configure

### ISSUE THREAD

**Issue by marcindulak** [edoapra/fedpkg#6]
Building https://github.com/edoapra/ga/commit/d8a4544067f36fec55c78e21336141bad4a5e455 with a modified https://github.com/edoapra/fedpkg/blob/210d2d7fa8c5be67a02ee4d8eebe9e5f038a508a/ga/ga.spec (in addition to the change below, the patches are no longer needed)

```
diff --git a/ga/ga.spec b/ga/ga.spec
index d96ea4c..93a56b2 100644
--- a/ga/ga.spec
+++ b/ga/ga.spec
@@ -19,7 +19,7 @@ Patch3:       mkl_pdstedc.patch
 Patch4:        pgcc_f77object.patch
 ExclusiveArch: %{ix86} x86_64
 BuildRequires: openmpi-devel, %{mpich_name}-devel, gcc-c++, gcc-gfortran, hwloc-devel
-BuildRequires: libibverbs-devel, openblas-devel, openssh-clients, dos2unix
+BuildRequires: libibverbs-devel, openblas-devel, openssh-clients, dos2unix, automake, libtool
 
 %define ga_desc_base \
 The Global Arrays (GA) toolkit provides an efficient and portable \
@@ -145,6 +145,7 @@ Conflicts: %{name}-openmpi-static
 %patch4 -p0
 
 pushd %{name}-%{ga_version}
+autoreconf -vif
 popd
 for i in mpich openmpi; do
   cp -a %{name}-%{ga_version} %{name}-%{version}-$i
```

**Comment by edoapra** [comment]
@marcindulak why do we need `autoreconf`?

**Comment by marcindulak** [comment]
I see now that there is a 5.7.1 release at https://github.com/edoapra/ga/releases which contains a tarball in addition to the source archives made by github tag. This additional tarball contains `configure`.

I was just building from https://github.com/edoapra/ga/commit/d8a4544067f36fec55c78e21336141bad4a5e455 directly.
`configure` is not part of the source there, so it needs to be created from `configure.ac`.

The question is how much "from source" we want to build ga. If ga release continue to include `configure` then we don't need this patch.

**Comment by edoapra** [comment]
Yes, let's always assume we are building from tarballs

**Comment by edoapra** [comment]
https://github.com/edoapra/fedpkg/issues/5#issuecomment-592740103

**Comment by edoapra** [comment]
I believe we can close this one
