### ISSUE TITLE
ga's 5.7.1 autoreconf fails on rhel6

### ISSUE THREAD

**Issue by marcindulak** [edoapra/fedpkg#7]
Using https://github.com/edoapra/ga/tree/d8a4544067f36fec55c78e21336141bad4a5e455

https://koji.fedoraproject.org/koji/taskinfo?taskID=41517880

```
autoreconf -vif
...
configure.ac:6: error: Autoconf version 2.67 or higher is required
```

rhel6 has `autoconf  2.63-5.1.el6`

**Comment by edoapra** [comment]
@marcindulak why do we need autoreconf? I would rather have the RPM use release tarballs

**Comment by edoapra** [comment]
Let's assume we always build from tarballs
See https://github.com/edoapra/fedpkg/issues/6
